from enum import Enum


class IntentType(str, Enum):
    # SCOPE
    DEFINE_SCOPE = "DEFINE_SCOPE"

    PROJECT_DESCRIPTION = "PROJECT_DESCRIPTION"

    ROLE_DEFINITION = "ROLE_DEFINITION"
    BUSINESS_GOALS = "BUSINESS_GOALS"
    CURRENT_PROCESS = "CURRENT_PROCESS"

    ROLE_FEATURES = "ROLE_FEATURES"
    SYSTEM_FEATURES = "SYSTEM_FEATURES"
    DATA_ENTITIES = "DATA_ENTITIES"
    INTEGRATIONS = "INTEGRATIONS"

    DESIGN_PREFERENCES = "DESIGN_PREFERENCES"
    REFERENCE_URLS = "REFERENCE_URLS"
    ASSETS_UPLOAD = "ASSETS_UPLOAD"

    SECURITY_REQUIREMENTS = "SECURITY_REQUIREMENTS"
    PERFORMANCE_REQUIREMENTS = "PERFORMANCE_REQUIREMENTS"
    CONCURRENCY_REQUIREMENTS = "CONCURRENCY_REQUIREMENTS"
    AVAILABILITY_REQUIREMENTS = "AVAILABILITY_REQUIREMENTS"
    CONSTRAINTS = "CONSTRAINTS"

    ADDITIONAL_INFO = "ADDITIONAL_INFO"
