from enum import Enum


class IntentType(str, Enum):
    # SCOPE
    DEFINE_SCOPE = "DEFINE_SCOPE"
    SCOPE_CLARIFICATION = "SCOPE_CLARIFICATION"
    SCOPE_INQUIRY = "SCOPE_INQUIRY"

    PROJECT_DESCRIPTION = "PROJECT_DESCRIPTION"
    MIGRATION_STRATEGY = "MIGRATION_STRATEGY"

    ROLE_DEFINITION = "ROLE_DEFINITION"
    BUSINESS_GOALS = "BUSINESS_GOALS"
    CURRENT_PROCESS = "CURRENT_PROCESS"

    ROLE_FEATURES = "ROLE_FEATURES"
    SYSTEM_FEATURES = "SYSTEM_FEATURES"
    SCREENS_PAGES = "SCREENS_PAGES"
    DATA_ENTITIES = "DATA_ENTITIES"
    INTEGRATIONS = "INTEGRATIONS"
    THIRD_PARTY_SERVICES = "THIRD_PARTY_SERVICES"

    DESIGN_PREFERENCES = "DESIGN_PREFERENCES"
    REFERENCE_URLS = "REFERENCE_URLS"
    INSPIRATION_URLS = "INSPIRATION_URLS"
    CURRENT_APP_URL = "CURRENT_APP_URL"
    ASSETS_UPLOAD = "ASSETS_UPLOAD"

    SECURITY_REQUIREMENTS = "SECURITY_REQUIREMENTS"
    COMPLIANCE_REQUIREMENTS = "COMPLIANCE_REQUIREMENTS"
    PERFORMANCE_REQUIREMENTS = "PERFORMANCE_REQUIREMENTS"
    CONCURRENCY_REQUIREMENTS = "CONCURRENCY_REQUIREMENTS"
    AVAILABILITY_REQUIREMENTS = "AVAILABILITY_REQUIREMENTS"
    TECH_STACK_PREFERENCE = "TECH_STACK_PREFERENCE"
    PROJECT_TIMELINE = "PROJECT_TIMELINE"
    CONSTRAINTS = "CONSTRAINTS"
    BUDGET = "BUDGET"

    ADDITIONAL_INFO = "ADDITIONAL_INFO"
